name: "02 - Infrastructure GitOps"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Infrastructure CD"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authentification AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::049618906674:role/petclinic-ci
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init
      
      # ÉTAPE AJOUTÉE : Scan de sécurité de l'IaC avec tfsec
      - name: Run tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working-directory: ./terraform
          soft-fail: true # Évite de bloquer complètement si vous avez de petits avertissements de sécurité hérités du TP3

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan
        env:
          # Injection dynamique du nom du dépôt actuel pour que Terraform l'associe à var.github_repo
          TF_VAR_github_repo: ${{ github.repository }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        env:
          # Également injecté à l'apply pour garantir la correspondance exacte
          TF_VAR_github_repo: ${{ github.repository }}